# golangci-lint configuration
run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - stylecheck
    - gosec
    - goconst
    - gocyclo
    - misspell
    - unparam
    - unconvert
    - prealloc

linters-settings:
  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  gosec:
    excludes:
      - G204  # Subprocess launched with variable
      - G304  # File path provided as taint input

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    # Exclude some linters from running on tests
    - path: _test\.go
      linters:
        - gocyclo
        - gosec
        - goconst
        - errcheck  # Allow ignoring errors in test code

    # Exclude magic number checks in tests
    - path: _test\.go
      text: "Magic number"

    # Allow long lines in test data
    - path: test/
      linters:
        - lll

    # Allow high complexity in packet analyzer (multi-layer detection logic)
    - path: analyzer\.go
      text: "cyclomatic complexity.*AnalyzePacketEx"

    # Allow high complexity in DHT node validation (detailed binary parsing)
    - path: detectors\.go
      text: "cyclomatic complexity.*CheckDHTNodes"

  max-issues-per-linter: 0
  max-same-issues: 0
