# golangci-lint configuration
run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - stylecheck
    - gosec
    - goconst
    - gocyclo
    - misspell
    - unparam
    - unconvert
    - prealloc
    - exportloopref

linters-settings:
  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  gosec:
    excludes:
      - G204  # Subprocess launched with variable
      - G304  # File path provided as taint input

issues:
  exclude-rules:
    # Exclude some linters from running on tests
    - path: _test\.go
      linters:
        - gocyclo
        - gosec
        - goconst

    # Exclude magic number checks in tests
    - path: _test\.go
      text: "Magic number"

    # Allow long lines in test data
    - path: test/
      linters:
        - lll

  max-issues-per-linter: 0
  max-same-issues: 0
